// A working list of countries for the Customer master's multi-select. Not exhaustive -
// covers the markets Adwaith Lakshmi commonly ships to; add more here as needed.
export const COUNTRIES = [
  'India',
  'United States',
  'United Kingdom',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Belgium',
  'Portugal',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Switzerland',
  'Austria',
  'Poland',
  'Ireland',
  'Greece',
  'Turkey',
  'Russia',
  'UAE',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Israel',
  'China',
  'Japan',
  'South Korea',
  'Hong Kong',
  'Taiwan',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Vietnam',
  'Indonesia',
  'Philippines',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Pakistan',
  'Australia',
  'New Zealand',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'Chile',
  'South Africa',
  'Egypt',
  'Nigeria',
  'Kenya',
] as const;
